---
# changed aws ECR
- name: Install Pip
  apt: pkg=python-pip state=present

- name: Install pexpect
  command: pip install pexpect
  when: aws_access_key_id is defined

- name: Install awscli
  command: pip install awscli
  when: aws_access_key_id is defined

- name: Create aws credentials
  expect:
    command: aws configure
    responses:
      (?i)aws\saccess: "{{aws_access_key_id}}"
      (?i)aws\ssecret: "{{aws_secret_access_key}}"
      (?i)region\sname: "us-west-1"
      (?i)output\sformat: "text"
  when: aws_access_key_id is defined
  
# changed aws ECR

- name: Authenticate to ECR
  shell: $(aws ecr get-login --region us-west-1 --no-include-email)
  when: aws_access_key_id is defined

- name: Pull editor Docker image
  command: /usr/bin/docker pull {{ docker_repository }}driver-editor:latest

- name: Build production editor app
  command: >
    /usr/bin/docker run
      --rm
      --name driver-editor
      --volume {{ editor_scripts_dir }}/config.js:{{ editor_scripts_dir }}/config.js
      --volume {{ editor_build_dir }}:{{ editor_build_dir }}
      --log-driver syslog
      {{ docker_repository }}driver-editor:latest
      build

- name: Create editor data container
  command: >
    /usr/bin/docker create
      --volume {{ editor_dir }}
      --name driver-editor
    {{ docker_repository }}driver-editor:latest

- name: Pull web Docker image
  command: /usr/bin/docker pull {{ docker_repository }}driver-web:latest

- name: Build production web app
  command: >
    /usr/bin/docker run
      --rm
      --name driver-web
      --volumes-from driver-editor
      --volume {{ editor_scripts_dir }}/config.js:{{ editor_scripts_dir }}/config.js
      --volume {{ web_scripts_dir }}/config.js:{{ web_scripts_dir }}/config.js
      --volume {{ web_dir }}/app/index.html:{{ web_dir }}/app/index.html
      --volume {{ web_build_dir }}:{{ web_build_dir }}
      --log-driver syslog
      {{ docker_repository }}driver-web:latest
      build

- name: Remove editor data container
  command: >
    /usr/bin/docker rm --volumes --force driver-editor
