---
- name: Create static files directory
  file: path={{ root_static_dir }}
        owner={{ driver_user }}
        group={{ driver_user }}
        mode=0775
        state=directory

- name: Create media files directory
  file: path={{ root_media_dir }}
        owner={{ driver_user }}
        group={{ driver_user }}
        mode=0775
        state=directory
# changed aws ECR
- name: Install Pip
  apt: pkg=python-pip state=present

- name: Install pexpect
  command: pip install pexpect
  when: aws_access_key_id is defined

- name: Install awscli
  command: pip install awscli
  when: aws_access_key_id is defined

- name: Create aws credentials
  expect:
    command: aws configure
    responses:
      (?i)aws\saccess: "{{aws_access_key_id}}"
      (?i)aws\ssecret: "{{aws_secret_access_key}}"
      (?i)region\sname: "us-west-1"
      (?i)output\sformat: "text"
  when: aws_access_key_id is defined

- name: Authenticate to ECR
  shell: $(aws ecr get-login --region us-west-1 --no-include-email)
  when: aws_access_key_id is defined
#changed ECR 

- name: Build application Docker image
  command: >
    docker build
      -f {{ root_app_dir }}/Dockerfile.base
      -t {{ docker_repository }}driver-app:{{ docker_image_tag }}
      {{ root_app_dir }}
  when: developing

- name: Build application Docker image (dev tools)
  command: >
    docker build
      -f {{ root_app_dir }}/Dockerfile.development
      -t {{ docker_repository }}driver-app:{{ docker_image_tag }}
      {{ root_app_dir }}
  when: developing

- name: Pull application Docker image
  command: /usr/bin/docker pull {{ docker_repository }}driver-app:{{ docker_image_tag }}
  when: staging or production

- name: Configure DRIVER application service definition
  template: src=upstart-app.conf.j2 dest=/etc/init/driver-app.conf

- name: Restart DRIVER application
  service: name=driver-app state=restarted

- name: Set up monit monitoring of driver-app container
  template: src=monit-driver-app.cfg.j2 dest=/etc/monit/conf.d/driver-app.cfg
  notify:
    - Restart monit

- name: Run Django collectstatic
  command: >
    /usr/bin/docker exec -i driver-app ./manage.py collectstatic --noinput

- name: Run Django migrations
  command: >
    /usr/bin/docker exec -i driver-app ./manage.py migrate

- { include: firewall.yml }
